language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
    - PACKAGE=xapi-idl
    - PINS="xapi-idl:."
    - DISTRO="debian-unstable"
    - OCAML_VERSION="4.07"
    - BASE_REMOTE_BRANCH="REQ-627"
    - BASE_REMOTE="https://github.com/xapi-project/xs-opam.git"
