language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
  - wget https://raw.githubusercontent.com/xapi-project/xapi-travis-scripts/v0.1/coverage.sh
script:
    - bash -ex .travis-docker.sh
sudo: required
services:
    - docker
env:
  global:
    - OCAML_VERSION=4.06
    - PINS="xcp:."
    - PACKAGE=xcp
    - DISTRO="debian-testing"
  matrix:
    - BASE_REMOTE=git://github.com/xapi-project/xs-opam \
      POST_INSTALL_HOOK="env TRAVIS=$TRAVIS TRAVIS_JOB_ID=$TRAVIS_JOB_ID TEST_DEPS="alcotest" TEST_CMD='jbuilder runtest --no-buffer' bash -ex coverage.sh"
    - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
matrix:
    fast_finish: true
    allow_failures:
        - env: EXTRA_REMOTES=git://github.com/xapi-project/xs-opam

